- name: Test Ansible
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    homedir: ./build
    container_registry: docker.io/library
  tasks:
    - name: "Create the directories"
      ansible.builtin.file:
        mode: "0755"
        path: "{{ homedir }}/{{ item }}"
        state: directory
      loop:
        - syscom

    - name: "Create the httpd syscom file"
      ansible.builtin.copy:
        mode: "0755"
        dest: "{{ homedir }}/syscom/index.html"
        content: |
          <html>
            <header>
              <title>SysAdmin.com</title>
            </header>
            <body>
              <p>This is the SysAdmin website hosted on the .com domain</p>
            </body>
          </html>


    - name: "Create the syscom container"
      containers.podman.podman_container:
        name: syscom
        image: "{{ container_registry }}/httpd:alpine3.20"
        volume:
          - "{{ homedir }}/syscom:/usr/local/apache2/htdocs:Z"
        rm: true
        state: created

    - name: "Create the sysorg container"
      containers.podman.podman_container:
        name: sysorg
        image: "{{ container_registry }}/httpd:alpine3.20"
        volume:
          - "{{ homedir }}/sysorg:/usr/local/apache2/htdocs:Z"
        rm: true
        state: created

    - name: Generate systemd unit file for postgres container
      containers.podman.podman_generate_systemd:
        name: syscom
        new: true
        no_header: true
        dest: /etc/systemd/system

    - name: Ensure postgres container is started and enabled
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.systemd:
        name: container-syscom
        daemon_reload: true
        state: started
        enabled: true
