---
- name: Test Ansible
  hosts: localhost
  connection: local
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: false
  tasks:
    - name: "Build the app image"
      containers.podman.podman_image:
        name: app
        path: ..
        build:
          force_rm: true
          format: oci
        state: present
        force: true

    - name: "Create super good secret"
      containers.podman.podman_secret:
        state: present
        name: some-secret
        data: "my super secret content"

    - name: "Delete previous version of container if exists"
      containers.podman.podman_container:
        name: app
        state: absent
        delete_time: 10

    - name: "Create the app container"
      containers.podman.podman_container:
        name: app
        image: localhost/app
        secrets:
          - some-secret,type=env,target=SECRET_ENV
        ports:
          - 8081:8080
        rm: true
        state: stopped

    - name: Generate systemd unit file for app container
      containers.podman.podman_generate_systemd:
        name: app
        new: true
        no_header: true
        dest: /etc/systemd/system

    - name: Ensure app container is started and enabled
      ansible.builtin.systemd:
        name: container-app
        daemon_reload: true
        state: restarted
        enabled: true
